### ISSUE TITLE
Log User Intention Completion History V1

### ISSUE THREAD

**Issue by shervine** [menchblogs/platform#2478]
TODO

- [ ] A link metadata variable that creates a history of each time the user completes their Action Plan intention
- [ ] This way, when a new intent is added to the tree, we'd know that the user had previously completed this and now its again incomplete, so we can notify them of the updated steps.
- [ ] Again when they finish, we would mark the second completion and wait for more updates, and the cycle continues.
- [ ] Notify users when they are switched to resume another top intent #2365
- [ ] Notify students when top intent is completed #2290
- [ ] Notify Students of Completed Intention Expansion #2289
